# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_importance',
            field=models.CharField(choices=[('LO', 'low'), ('ST', 'standard'), ('HI', 'high')], default='ST', max_length=10),
        ),
    ]
